### ISSUE TITLE
Kid_166.xnb does not exist.

### ISSUE THREAD

**Issue by fungunoid** [salvadorc17/Prince-Monogame#2]
Kid_166 is referenced in KID_sequence.xml but does not exist in Content/Sprites/Player/dos nor in Content/Sprites/Player/alternate. This causes runtime exceptions in Sequence.cs Line 70 (below). 

Please commit missing files, fix the sequences, or include the raw image files that the XNB files are based off of so someone else may see the sprites and figure out the correct sequence.

Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
ERROR:Content.Load<dContentRes>System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PrinceGame.Sequence.Initialize(ContentManager Content) in Prince-Monogame\PrinceGame\Animation\Sequence.cs:line 69CONFIG_SPRITE_KIDKid_166

**Comment by salvadorc17** [comment]
Who are you, and why interested in source?

**Comment by fungunoid** [comment]
I'd like to help because I'd like to be able to play this game again with the Mac graphics and music by using a controller like I use to do in Sand of Time on the XBox. You seem to have a decent start here.

The Visual Studio project file is, I assume, out of date. I had to change reference library versions, include the new sprite content directories, and make changes to the code to account for the changes you made in the content folders to get it to build without errors. As you can guess from the above, I was able to get the game up and running. Seems like an intro sequence works fine, but I get a loop of runtime exceptions because of the missing 166 file with a black screen when the game is supposed to run. 

I found the source code that you based this off of (originally in VB, correct?) and it looks like you're straight porting it to MonoGame and C#. That source didn't have the Kid_166 file either. I looked at Jordan Mechner's source code as well, and it looks like the VB code pretty much just formatted Mechner's original sequence table into XML. I don't know how to rip that frame from the binary files Mechner posted though. That's old stuff. The VB code did have some sprite frames in PNG format though for the dos version. I can try to look through those and match up what 166 should be, or is closest too. I just don't know what ALERTSTAND means in terms of the character pose/action. princed.org also has some tools to extract images from the DOS data files, so maybe I can find it in there as well.

**Comment by salvadorc17** [comment]
I have fixed problem with the missing sprites, but if you want to do changes or updates to newer version, will need to fork your own repository, im currently only interested in code to allow game engine completion.

**Comment by fungunoid** [comment]
Then why don't you commit your changes to GitHub?

**Comment by salvadorc17** [comment]
Was a mistake i forgot to fix, but anyway this is not really issue.
